version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands: 
      - echo "Installing dependecies...."
      - npm install 
      - npm install -g @angular/cli
  build:
    commands: 
      - echo "Building the project now...."
      - ng build --prod
  post_build:
    commands:
      - echo "Updating artifact in the S3 bucket...."
      - aws s3 sync dist/angular-aws/ s3://angular-aws-simple-app-2022 --delete